services:
  frontend:
    build:
      context: ./frontend
    container_name: movie_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - movie-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: movie_backend
    ports:
      - "5000:5000"
    networks:
      - movie-network
    restart: unless-stopped

networks:
  movie-network:
    driver: bridge